import "./globals.css";
import type { Metadata } from "next";

import { TheFooter } from "@/components/TheFooter";
import { TheHeader } from "@/components/TheHeader";
import { Providers } from "@/components/Providers";
import s from "../styles/global.module.css";
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={s.bodyElement}>
        <Providers>
          <TheHeader />
          <main className={s.container}>{children}</main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
